# Edit COORDINATOR_IP before every demo session

COORDINATOR_IP = 'IP_ADDRESS_OF_COORDINATOR'
COORDINATOR_PORT = 5000
TOTAL_ROUNDS = 5
LOCAL_EPOCHS = 2
BATCH_SIZE = 32
LEARNING_RATE = 1e-3
DATA_PATH = './data/'
 